---
- name: Create demo app 
  kubernetes.core.k8s_info:
#        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}" 
#    kubeconfig: "kubeconfig" 
    kind: Pod
    namespace: aap-containergroup-namespace
  register: myocp4_pod
#  delegate_to: localhost

- name: Print output
  debug: 
    msg: "{{ myocp4_pod }}"
