- name: Listen and reading message from Kafka topic
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: ocpmanagement.ocpdemo.ghost.lenovolabs
        port: 9092
        topic: connect-dnf
        group_id:

#  rules:
#    - name: Kafka telnet dnf log
#      condition: event.body.payload is search("\sDEBUG\sRemoved:\stelnet",ignorecase=true) or event.body.payload is search("\sDEBUG\sRemoved:\szip",ignorecase=true)
#      action:
#        debug:
#          var: "{{ event.body.payload }}"


  rules:
    - name: Kafka dnf log messaging
      condition: event.body.payload is search("\sDEBUG\sRemoved:\stelnet",ignorecase=true) or event.body.payload is search("\sDEBUG\sRemoved:\szip",ignorecase=true)
      action:
        run_job_template:
          name: kafka-eda-demo-template
          organization: Default


#        run_job_template:
#          name: kafka-eda-demo-template
#          organization: Default

#    - name: httpd service down detected
#      condition: event.schema is defined
#      action:
#        run_job_template:
#          name: kafka-eda-demo-template
#          organization: Default

