- name: Listen and reading message from Kafka topic
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: ocpmanagement.ocpdemo.ghost.lenovolabs
        port: 9092
        topic: connect-httpd
        group_id:

  rules:
    - name: httpd service down detected
      condition: event.payload.text == "shutting down"
      action:
        run_job_template:
          name: kafka-eda-demo-template
          organization: Default
