- name: Listen for newly added namespace resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
        namespace: eda
  rules:
    - name: Trigger action
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: eda-demo-template
          organization: Default
