- name: Listen and polling URL 
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://172.16.15.6/index.html
        delay: 20

  rules:
    - name: Website is up!!
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: url-check-httpd-retain-template
          organization: Default

    - name: Website is down!! 
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: url-check-httpd-retart-template
          organization: Default


