- name: Listen and polling URL 
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://172.16.15.6/index.html
        delay: 20

  rules:
#    - name: Website is up!!
#      condition: event.url_check.status == "up"
#      action:
#        run_job_template:
#          name: url-check-httpd-retain-template
#          organization: Default

    - name: Web service is down!! 
      condition: event.url_check.error_msg == "Cannot connect to host"
      action:
        run_job_template:
          name: url-check-httpd-retart-template
          organization: Default


